app:
  port: 8080
redis:
  ip: "127.0.0.1"
  port: 6379
  db: 0
  data_prefix: "ipvizualizator"
users:
# IDs of users described in this config must be less than 1000
- id: 1
  username: "admin"
  admin: true
  authorization: "asdf1234567890"
